#!/usr/bin/env python3
"""
data/fonts.json 生成器 (フォントメタデータ)

data フォルダ配下のフォント (*.ttf / *.otf) を走査し、
- family : name テーブルの Typographic Family (nameID 16) or Family (nameID 1)
- ranges : cmap の収録コードポイントを区間 [start,end] へ圧縮 (coverage・手軽版)
- scripts: 収録コードポイントから粗く分類した ISO15924 スクリプト
- flags  : カラー絵文字(CBDT/COLR/sbix)・等幅 等のヒント
を持つ fonts.json を出力する。

依存: fonttools  (pip install fonttools)

使い方:
  python tools/fontgen/gen_fonts_json.py --fonts-dir src/core/data/fonts \
         --root src/core/data --out src/core/data/fonts.json
  # file はメタデータ(fonts.json)からの相対 = --root からの相対で記録される
"""
import argparse, json, os, sys

# 主要 Unicode ブロック -> ISO15924 (粗い分類。必要に応じて拡張)
BLOCKS = [
    (0x0000, 0x024F, "Latn"), (0x0370, 0x03FF, "Grek"), (0x0400, 0x04FF, "Cyrl"),
    (0x0590, 0x05FF, "Hebr"), (0x0600, 0x06FF, "Arab"),
    (0x0E00, 0x0E7F, "Thai"), (0x1100, 0x11FF, "Hang"),
    (0x3040, 0x309F, "Hira"), (0x30A0, 0x30FF, "Kana"),
    (0x3400, 0x4DBF, "Hani"), (0x4E00, 0x9FFF, "Hani"), (0xF900, 0xFAFF, "Hani"),
    (0x20000, 0x2FA1F, "Hani"),
    (0xAC00, 0xD7AF, "Hang"),
    (0x2600, 0x27BF, "Zsye"), (0x1F000, 0x1FAFF, "Zsye"),
]

def script_of(cp):
    for lo, hi, s in BLOCKS:
        if lo <= cp <= hi:
            return s
    return None

def compress(cps, max_ranges=64):
    cps = sorted(cps)
    ranges = []
    if not cps:
        return ranges
    start = prev = cps[0]
    for cp in cps[1:]:
        if cp == prev + 1:
            prev = cp
        else:
            ranges.append([start, prev]); start = prev = cp
    ranges.append([start, prev])
    # 区間が多すぎる場合は隣接ギャップの小さい順にマージして間引く
    while len(ranges) > max_ranges:
        # 最小ギャップの隣接区間を統合
        gi = min(range(len(ranges) - 1),
                 key=lambda i: ranges[i + 1][0] - ranges[i][1])
        ranges[gi] = [ranges[gi][0], ranges[gi + 1][1]]
        del ranges[gi + 1]
    return ranges

def analyze(path):
    from fontTools.ttLib import TTFont
    f = TTFont(path, fontNumber=0, lazy=True)
    # 名前情報。family は純粋な family 名 (Typographic Family 優先)。
    # 従来は非 Regular の subfamily を family へ連結していたが、スキーマ拡張で
    # subfamily を別フィールドにし、旧表記 "family subfamily" は互換 alias に回す
    name = f["name"]
    fam = name.getDebugName(16) or name.getDebugName(1) or os.path.splitext(os.path.basename(path))[0]
    sub = name.getDebugName(17) or name.getDebugName(2) or ""
    info = {"family": fam}
    if sub:
        info["subfamily"] = sub
    # krkrz classic (FreeType) の face 名は "family subfamily" 連結 (例
    # "Noto Color Emoji Regular")。実 face 名でも引けるよう常に alias に出す
    if sub and f"{fam} {sub}" != fam:
        info["aliases"] = [f"{fam} {sub}"]
    full = name.getDebugName(4)
    if full and full != fam:
        info["fullName"] = full
    ps = name.getDebugName(6)
    if ps:
        info["postScriptName"] = ps
    # スタイル (OS/2)
    if "OS/2" in f:
        os2 = f["OS/2"]
        info["weight"] = int(os2.usWeightClass)
        if os2.fsSelection & 0x01:
            info["italic"] = True
    # coverage
    cps = set(f.getBestCmap().keys())
    scripts = sorted({s for s in (script_of(c) for c in cps) if s})
    ranges = compress(cps)
    flags = []
    tables = set(f.reader.tables.keys())
    if tables & {"CBDT", "sbix", "COLR"}:
        flags += ["emoji", "color"]
    elif "Zsye" in scripts:
        flags += ["emoji"]
    if "post" in f and getattr(f["post"], "isFixedPitch", 0):
        flags += ["monospace"]
    f.close()
    return info, scripts, ranges, flags

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts-dir", required=True, help="走査するフォントフォルダ")
    ap.add_argument("--root", required=True, help="file をこのフォルダからの相対で記録")
    ap.add_argument("--out", required=True, help="出力 fonts.json")
    a = ap.parse_args()

    entries = []
    for fn in sorted(os.listdir(a.fonts_dir)):
        if os.path.splitext(fn)[1].lower() not in (".ttf", ".otf", ".ttc"):
            continue
        p = os.path.join(a.fonts_dir, fn)
        try:
            info, scripts, ranges, flags = analyze(p)
        except Exception as e:
            print(f"skip {fn}: {e}", file=sys.stderr); continue
        rel = os.path.relpath(p, a.root).replace("\\", "/")
        ent = {"file": rel}
        ent.update(info)
        if scripts: ent["scripts"] = scripts
        if flags:   ent["flags"] = flags
        if ranges:  ent["ranges"] = ranges
        entries.append(ent)
        print(f"{fn}: family='{info['family']}' subfamily='{info.get('subfamily','')}' "
              f"weight={info.get('weight')} scripts={scripts} flags={flags} ranges={len(ranges)}")

    doc = {"version": 1,
           "comment": "generated by tools/fontgen/gen_fonts_json.py",
           "fonts": entries}
    with open(a.out, "w", encoding="utf-8") as f:
        json.dump(doc, f, ensure_ascii=False, indent=2)
    print(f"wrote {a.out} ({len(entries)} font(s))")

if __name__ == "__main__":
    main()
