# packinone_absorb() - 個別プラグインのソースを詰め合わせ DLL へ取り込む
#
# packinone / packinoneWin32 の両方から include する共通部。
#
# 取り込むソースには per-source で
#   TVP_STATIC_PLUGIN       … ncbind / simplebinder の自動登録リストを名前で分ける
#                             + krkrz_plugin_<名前>() の登録エントリを生やす
#   TVP_PLUGIN_NAME=<名前>  … その名前
#   V2Link / V2Unlink / DllEntryPoint … 名前衝突を避けるため改名
# を与える。 詰め合わせ側の V2Link は bundle_impl.h が持つ。
#
# ⚠ バインダ (ncbind.cpp / v2link.cpp) には V2Link と登録エントリが入っているので、
#   **プラグインごとに別コンパイル**する (生成した薄いラッパ経由)。
#
# 詳細は src/packinone/README.md。

if(NOT DEFINED PACKINONE_ABSORB_CMAKE_INCLUDED)
set(PACKINONE_ABSORB_CMAKE_INCLUDED TRUE)

set(PACKINONE_DIR         ${CMAKE_CURRENT_LIST_DIR})
set(PACKINONE_PLUGINS_DIR ${CMAKE_CURRENT_LIST_DIR}/../plugins)
set(PACKINONE_NCBIND_CPP  ${PACKINONE_PLUGINS_DIR}/ncbind/ncbind.cpp)
set(PACKINONE_V2LINK_CPP  ${PACKINONE_PLUGINS_DIR}/simplebinder/v2link.cpp)

set(TPSTUB_DIR ${PACKINONE_PLUGINS_DIR}/tp_stub CACHE PATH "Path to tp_stub directory")
if(NOT COMMAND krkrz_plugin)
    include(${TPSTUB_DIR}/krkrz.cmake)
endif()

# packinone_absorb(<名前>
#     [NCBIND | SIMPLEBIND]      使っているバインダ
#     [DIR      <path>]          ソースの置き場 (既定 ../plugins/<名前>)
#     [SOURCES  <src...>]        DIR からの相対パス
#     [INCLUDES <dir...>]        DIR からの相対パス、または絶対パス
#     [DEFINITIONS <def...>])
#
# 呼び出し側の PACKINONE_SOURCES に取り込んだソースを積んでいく。
function(packinone_absorb name)
    cmake_parse_arguments(A "NCBIND;SIMPLEBIND" "DIR" "SOURCES;INCLUDES;DEFINITIONS" ${ARGN})

    if(NOT A_DIR)
        set(A_DIR ${PACKINONE_PLUGINS_DIR}/${name})
    endif()
    get_filename_component(A_DIR "${A_DIR}" ABSOLUTE)

    set(defs "TVP_STATIC_PLUGIN;TVP_PLUGIN_NAME=${name};V2Link=V2Link_${name};V2Unlink=V2Unlink_${name};DllEntryPoint=DllEntryPoint_${name}")
    list(APPEND defs ${A_DEFINITIONS})

    # ⚠ 取り込むプラグイン自身のヘッダを先に見せる (tp_stub / ncbind の古い写しを拾わないため)
    set(incs "${A_DIR}")
    foreach(inc ${A_INCLUDES})
        if(IS_ABSOLUTE "${inc}")
            list(APPEND incs "${inc}")
        else()
            list(APPEND incs "${A_DIR}/${inc}")
        endif()
    endforeach()
    list(APPEND incs
        "${PACKINONE_PLUGINS_DIR}/ncbind"
        "${PACKINONE_PLUGINS_DIR}/simplebinder"
        "${PACKINONE_PLUGINS_DIR}")

    set(files "")
    foreach(src ${A_SOURCES})
        list(APPEND files ${A_DIR}/${src})
    endforeach()

    # バインダはプラグインごとにコンパイルする必要があるので薄いラッパを生成する
    set(binder "")
    if(A_NCBIND)
        set(binder ${PACKINONE_NCBIND_CPP})
    elseif(A_SIMPLEBIND)
        set(binder ${PACKINONE_V2LINK_CPP})
    endif()
    if(binder)
        set(wrapper ${CMAKE_CURRENT_BINARY_DIR}/binder_${name}.cpp)
        file(WRITE ${wrapper}
             "// generated by src/packinone/absorb.cmake\n"
             "#include \"${binder}\"\n")
        list(APPEND files ${wrapper})
    endif()

    set_source_files_properties(${files} PROPERTIES
        COMPILE_DEFINITIONS "${defs}"
        INCLUDE_DIRECTORIES "${incs}")

    set(PACKINONE_SOURCES ${PACKINONE_SOURCES} ${files} PARENT_SCOPE)
endfunction()

endif()
